name: cloudinary_flutter
description: Cloudinary is a cloud service that offers a solution to a web application's entire image management pipeline
version: 0.0.5
homepage: https://www.cloudinary.com
repository: https://github.com/cloudinary/cloudinary_flutter

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloudinary_url_gen: ^0.9.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0