name: cloudinary_flutter
description: Cloudinary is a cloud service that offers a solution to a web application's entire image management pipeline
version: 0.0.1
homepage: https://www.cloudinary.com
repository: https://github.com/cloudinary/cloudinary_flutter


environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloudinary_dart: ^0.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0